apiVersion: v1
kind: ServiceAccount
metadata:
  name: ratingsboard-sa
  namespace: ratingsboard
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/ratingsboard-secrets-reader
