apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-api-sa
  namespace: {{ .Values.global.namespace }}
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-api
  namespace: {{ .Values.global.namespace }}
  labels: { app: transaction-api }
spec:
  replicas: {{ .Values.transactionApi.replicas }}
  selector: { matchLabels: { app: transaction-api } }
  strategy: { type: RollingUpdate, rollingUpdate: { maxUnavailable: 0, maxSurge: 1 } }
  template:
    metadata: { labels: { app: transaction-api } }
    spec:
      serviceAccountName: transaction-api-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: transaction-api
          image: "{{ .Values.global.imageRegistry }}/transaction-api:{{ .Values.global.imageTag }}"
          ports: [{ containerPort: 8080 }]
          envFrom: [{ configMapRef: { name: finledger-config } }]
          env:
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: finledger-secrets, key: DB_PASSWORD } }
          startupProbe: { httpGet: { path: /actuator/health, port: 8080 }, failureThreshold: 30, periodSeconds: 5 }
          readinessProbe: { httpGet: { path: /actuator/health, port: 8080 }, periodSeconds: 5 }
          livenessProbe: { httpGet: { path: /actuator/health, port: 8080 }, periodSeconds: 10 }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
          volumeMounts: [{ name: tmp, mountPath: /tmp }]
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits: { cpu: "1", memory: "1Gi" }
      volumes: [{ name: tmp, emptyDir: {} }]
---
apiVersion: v1
kind: Service
metadata: { name: transaction-api, namespace: {{ .Values.global.namespace }} }
spec:
  selector: { app: transaction-api }
  ports: [{ port: 80, targetPort: 8080 }]
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: { name: transaction-api-pdb, namespace: {{ .Values.global.namespace }} }
spec:
  minAvailable: {{ .Values.transactionApi.minAvailable }}
  selector: { matchLabels: { app: transaction-api } }
